### PR TITLE
minor tweaks

### PR DESCRIPTION
**Pull request by NotAShelf**
- fixed typos
- fixed grammar

### CODE REVIEW

**Comment by NotAShelf** [comment]
- removed `.idea` directory as it does not need to be kept in the repository

**Comment by NotAShelf** [comment]
hi, feel absolutely free to use the fixed readme - in fact, I will update it again to suit the latest version of the plugin

and you can add `.idea/` to your `.gitignore` and then delete it from the repository to keep it removed

**Comment by NotAShelf** [comment]
additionally, you can merge this pull request (when it's done) and it'll be fixed

**Comment by MXTPLUGINS** [comment]
> hi, feel absolutely free to use the fixed readme - in fact, I will update it again to suit the latest version of the plugin
> 
> and you can add `.idea/` to your `.gitignore` and then delete it from the repository to keep it removed

Thank you!

**Comment by MXTPLUGINS** [comment]
> additionally, you can merge this pull request (when it's done) and it'll be fixed

Thanks! I have edited the README.md manually because I'm getting some errors/problems while trying to merge pull request

**Pull request closed without merging**
